# Assignment For This Week
Develop program menggunakan algoritma k-means clustring untuk data 20newsgroups 3 kelas: Sport, Religion dan Technology. Sumber materi dapat diakses di https://tita.lecturer.pens.ac.id/TextMining_SDT/M10.%20Text%20Clustering/Text%20Clustering%20with%20TF-IDF%20in%20Python.pdf

Dengan ketentuan:

#### A. Data dalam bentuk Bag of Words
1. menggunakan rumus jarak Euclidean Distance
2. menggunakan rumus jarak Cosine Similarity

### B. Data dalam bentuk TF/IDF
1. menggunakan rumus jarak Euclidean Distance
2. menggunakan rumus jarak Cosine Similarity

### C. Data dalam bentuk Count Vectorizer
1. menggunakan rumus jarak Euclidean Distance
2. menggunakan rumus jarak Cosine Similarity

#### D. Data dalam bentuk Vocabulary menggunakan rumus jarak Jaccard Index

Buat analisa hasil klaster menggunakan metric performance DBI dan Silhoute score. 
Sajikan dalma bentuk presentasi. Unggah file ppt nya.

# Library

In [59]:
# import the dataset from sklearn
from sklearn.datasets import fetch_20newsgroups
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.decomposition import PCA
from sklearn import metrics

# import other required libs
import pandas as pd
import numpy as np

# string manipulation libs
import re
import string
import nltk
from nltk.corpus import stopwords

# viz libs
import matplotlib.pyplot as plt
import seaborn as sns

# Dataset

In [2]:
for i in fetch_20newsgroups().target_names:
    print(i)

alt.atheism
comp.graphics
comp.os.ms-windows.misc
comp.sys.ibm.pc.hardware
comp.sys.mac.hardware
comp.windows.x
misc.forsale
rec.autos
rec.motorcycles
rec.sport.baseball
rec.sport.hockey
sci.crypt
sci.electronics
sci.med
sci.space
soc.religion.christian
talk.politics.guns
talk.politics.mideast
talk.politics.misc
talk.religion.misc


In [55]:
categories = [
 'comp.graphics',
 'comp.os.ms-windows.misc',
 'rec.sport.hockey',
 'rec.sport.baseball',
 'alt.atheism',
 'soc.religion.christian'
]
dataset = fetch_20newsgroups(subset='all', categories=categories, shuffle=True, remove=('headers', 'footers', 'quotes'))
df = pd.DataFrame(dataset.data, columns=["corpus"])
df

corpus
0     whitsebd@nextwork.rose-hulman.edu (Bryan Whits...
1     \n\n\nActually, there was very little to the b...
2     \nI guarantee that if Bonds wins the MVP the G...
3     Hi everybody out there,\nI just got the third ...
4     \n:      For all the problems technology has c...
...                                                 ...
5742  \n\nThat's the whole point, David.  As spirits...
5743  \n\n\n\n\nYes, these last couple of months the...
5744  only\nappreciated.\n\n\nPierre Turgeon, formel...
5745  NOTE: Saturday, April 20th's scores should be ...
5746                                                 \n

[5747 rows x 1 columns]

In [56]:
def preprocess_text(text: str, remove_stopwords: bool) -> str:
    # remove links
    text = re.sub(r"http\S+", "", text)
    # remove special chars and numbers
    text = re.sub("[^A-Za-z]+", " ", text)
    # remove stopwords
    if remove_stopwords:
        # 1. tokenize
        tokens = nltk.word_tokenize(text)
        # 2. check if stopword
        tokens = [w for w in tokens if not w.lower() in stopwords.words("english")]
        # 3. join back together
        text = " ".join(tokens)
    # return text in lower case and stripped of whitespaces
    text = text.lower().strip()
    return text

In [57]:
df['cleaned'] = df['corpus'].apply(lambda x: preprocess_text(x, remove_stopwords=True))
df.tail(5)

corpus  \
5742  \n\nThat's the whole point, David.  As spirits...   
5743  \n\n\n\n\nYes, these last couple of months the...   
5744  only\nappreciated.\n\n\nPierre Turgeon, formel...   
5745  NOTE: Saturday, April 20th's scores should be ...   
5746                                                 \n   

                                                cleaned  
5742  whole point david spirits separated bodies liv...  
5743  yes last couple months kinngs failed show one ...  
5744  appreciated pierre turgeon formely sabres isle...  
5745  note saturday april th scores sent coming frid...  
5746

# A. Bag Of Words

In [58]:
cv = CountVectorizer(binary=True)
X = cv.fit_transform(df['cleaned']).toarray()
print(X)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


# B. TF/IDF

# C. Count Vectorizer

# D. Jaccard Index